image: gradle:7.6-jdk17

stages:
  - build
  - test
  - analyze

variables:
  SONAR_HOST_URL: "http://localhost:9000"
  SONAR_TOKEN: "sqp_a59dd3c29c2da322ddc94591d4751ecf674b8302"

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew clean assemble

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/index.html

sonarqube:
  stage: analyze
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=TasksManager -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CI_COMMIT_REF_NAME
